"""
Nura - Admin Schemas
Pydantic schemas for administrative lifecycle operations requests and responses
"""

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, EmailStr, Field, ConfigDict

from app.schemas.observability import AuditLogResponse
from app.models.user import UserResponse


class AdminCreateRequest(BaseModel):
    """Schema for creating a new administrator account"""
    full_name: str = Field(..., min_length=1, max_length=100, description="Administrator's full name")
    email: EmailStr = Field(..., description="Administrator's email address")


class AdminCreateResponse(BaseModel):
    """Schema for administrator account creation response (includes temporary password)"""
    id: str = Field(..., description="User ID")
    full_name: str = Field(..., description="Full name")
    email: str = Field(..., description="Email address")
    role: str = Field("admin", description="User role")
    is_active: bool = Field(..., description="Account active status")
    email_verified: bool = Field(..., description="Email verification status")
    created_at: datetime = Field(..., description="Account creation timestamp")
    temporary_password: str = Field(..., description="Plaintext temporary password generated by the system")


class AdminDetailResponse(BaseModel):
    """Schema for administrator details page (profile, status, and audit events)"""
    profile: UserResponse = Field(..., description="User profile details")
    account_status: dict = Field(..., description="Account status details (active, verified)")
    audit_summary: List[AuditLogResponse] = Field(default_factory=list, description="Recent audit log events involving this administrator")
