"""
Nura - Chat Streaming Service
Handles real-time SSE stream delivery of orchestrator messages
"""

import time
import asyncio
import logging
from typing import AsyncGenerator

from app.models.chat import (
    ChatMessageCreate,
    MessageRole,
    ChatSessionUpdate,
    SessionStatus,
)
from app.schemas.chat import ChatStreamChunk
from app.schemas.orchestrator import AIExecuteRequest
from app.repositories.chat_session_repository import ChatSessionRepository
from app.repositories.chat_message_repository import ChatMessageRepository
from app.services.chat_message_service import ChatMessageService
from app.services.chat_session_service import ChatSessionService
from app.services.chat.context_builder import build_conversation_context
from app.services.multi_agent_orchestrator import MultiAgentOrchestrator

logger = logging.getLogger(__name__)


class ChatStreamingService:
    """Orchestrates token-by-token message streaming via Server-Sent Events"""

    def __init__(
        self,
        chat_session_repository: ChatSessionRepository,
        chat_message_repository: ChatMessageRepository,
        chat_message_service: ChatMessageService,
        chat_session_service: ChatSessionService,
        orchestrator: MultiAgentOrchestrator,
    ):
        self.chat_session_repository = chat_session_repository
        self.chat_message_repository = chat_message_repository
        self.chat_message_service = chat_message_service
        self.chat_session_service = chat_session_service
        self.orchestrator = orchestrator

    async def stream_chat_message(
        self,
        session_id: str,
        patient_id: str,
        message: str,
        debug_mode: bool = False
    ) -> AsyncGenerator[str, None]:
        """
        Runs the Multi-Agent Orchestrator and yields chunks formatted as SSE data streams.
        Gracefully handles cancellation and buffers the finalized text to store at the end.
        """
        # 1. Validation
        session = await self.chat_session_repository.get(session_id)
        if not session or session.status == SessionStatus.DELETED:
            err_chunk = ChatStreamChunk(type="error", error="Session not found or deleted")
            yield f"data: {err_chunk.model_dump_json()}\n\n"
            return
        if session.patient_id != patient_id:
            err_chunk = ChatStreamChunk(type="error", error="Forbidden access to session")
            yield f"data: {err_chunk.model_dump_json()}\n\n"
            return

        # 2. Persist User Message
        from app.schemas.chat import ChatMessageCreate as CreateSchema
        user_msg_schema = CreateSchema(
            session_id=session_id,
            patient_id=patient_id,
            role=MessageRole.USER,
            content=message.strip(),
        )
        await self.chat_message_service.create_message(user_msg_schema)

        # Yield stream initiation token
        init_chunk = ChatStreamChunk(type="token", content="")
        yield f"data: {init_chunk.model_dump_json()}\n\n"

        # 3. Compile context
        context = await build_conversation_context(
            chat_message_repository=self.chat_message_repository,
            session_id=session_id,
            current_message=message.strip(),
            session_metadata=session.metadata or {},
            limit=20
        )

        # 4. Invoke Multi-Agent Orchestrator
        start_time = time.time()
        orchestrator_req = AIExecuteRequest(
            query=message.strip(),
            patient_id=patient_id,
            session_id=session_id,
            debug_mode=debug_mode,
            metadata={
                "conversation_history": context,
                "chat_session_title": session.title
            }
        )

        try:
            contract = await self.orchestrator.execute(orchestrator_req, user_id=patient_id, role="patient")
            latency_ms = (time.time() - start_time) * 1000.0

            if not contract.success:
                err_chunk = ChatStreamChunk(type="error", error=contract.response or "AI Orchestration failed")
                yield f"data: {err_chunk.model_dump_json()}\n\n"
                return

            response_text = contract.response or "No response generated by assistant."

            # 5. Stream tokens/characters to client
            # Chunk by chunk to create a smooth streaming user experience
            chunk_size = 4
            for i in range(0, len(response_text), chunk_size):
                # Check cancellation
                if asyncio.current_task() and asyncio.current_task().cancelled():
                    raise asyncio.CancelledError()

                chunk = response_text[i:i+chunk_size]
                tok_chunk = ChatStreamChunk(type="token", content=chunk)
                yield f"data: {tok_chunk.model_dump_json()}\n\n"
                await asyncio.sleep(0.01)

            # 6. Store completed Assistant Response in MongoDB (once fully complete)
            assistant_msg_schema = CreateSchema(
                session_id=session_id,
                patient_id=patient_id,
                role=MessageRole.ASSISTANT,
                content=response_text,
                citations=contract.citations,
                token_usage=contract.usage,
                latency_ms=int(latency_ms),
                metadata={
                    "agent": contract.agent,
                    "intent": contract.intent,
                    "cost": contract.cost,
                }
            )
            await self.chat_message_service.create_message(assistant_msg_schema)

            # Update parent session metadata (total cost, last agent used)
            sess_update = ChatSessionUpdate(
                total_cost=session.total_cost + contract.cost,
                last_agent_used=contract.agent or "UnknownAgent",
            )
            await self.chat_session_repository.update(session_id, sess_update)

            # 7. Yield final metadata payload
            meta_chunk = ChatStreamChunk(
                type="metadata",
                agent_used=contract.agent,
                citations=contract.citations,
                usage=contract.usage,
                latency_ms=latency_ms,
                cost=contract.cost
            )
            yield f"data: {meta_chunk.model_dump_json()}\n\n"

        except asyncio.CancelledError:
            logger.warning(f"SSE client stream cancelled or disconnected for session: {session_id}")
            # Do not persist assistant message since stream was cancelled mid-way
            raise
        except Exception as e:
            logger.exception(f"Unexpected error in chat streaming service: {e}")
            err_chunk = ChatStreamChunk(type="error", error=f"Internal Server Error: {str(e)}")
            yield f"data: {err_chunk.model_dump_json()}\n\n"
